### ISSUE TITLE
[Server] Can't connect to bridge

### ISSUE THREAD

**Issue by rafaelmagu** [iancmcc/ouimeaux#102]
Seeing the following traceback when running `wemo server` in my network:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/socketio/virtsocket.py", line 403, in _receiver_loop
    retval = pkt_ns.process_packet(pkt)
  File "/usr/local/lib/python2.7/dist-packages/socketio/namespace.py", line 155, in process_packet
    return self.process_event(packet)
  File "/usr/local/lib/python2.7/dist-packages/socketio/namespace.py", line 225, in process_event
    return self.call_method_with_acl(method_name, packet, *args)
  File "/usr/local/lib/python2.7/dist-packages/socketio/namespace.py", line 240, in call_method_with_acl
    return self.call_method(method_name, packet, *args)
  File "/usr/local/lib/python2.7/dist-packages/socketio/namespace.py", line 282, in call_method
    return method(*args)
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux/server/__init__.py", line 130, in on_statechange
    ENV.get(data['name']).set_state(data['state'])
AttributeError: 'Bridge' object has no attribute 'set_state'
<Greenlet at 0x7f30dbf990f0: <bound method Socket._receiver_loop of <socketio.virtsocket.Socket object at 0x7f30e001ac50>>> failed with AttributeError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
<Greenlet at 0x7f30dbf99050: <Flask 'ouimeaux.server'>({'HTTP_COOKIE': 'wanted_view=thumb; manage_view=th, <function <lambda> at 0x7f30dbfa3500>)> failed with ValueError
```

I can use `wemo light ... on/off` directly without an issue.

**Comment by rafaelmagu** [comment]
Forgot to mention: I have two LED lights attached to the bridge.

**Comment by gosku** [comment]
same problem here. I can use the api, but the web shows no devices. Same traceback as rafaelmagu

**Comment by payneardo** [comment]
same issue here I have 4 lights connected to a bridge, can use them using terminal but web crashes when I click on the bridge and have to refresh the page and the switch works then with no issues unless I click on the bridge

error I am getting is 

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gevent-1.1b5-py2.7-macosx-10.10-intel.egg/gevent/greenlet.py", line 523, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Python/2.7/site-packages/Flask_RESTful-0.3.4-py2.7.egg/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
<Greenlet at 0x10c5e6f50: <Flask 'ouimeaux.server'>({'HTTP_COOKIE': 'advanced_toggle_checked=; wanted_, <function <lambda> at 0x10c7bb1b8>)> failed with ValueError

**Comment by rafaelmagu** [comment]
Abandoned this project in favour of Home Assistant and Homebridge.
