### ISSUE TITLE
raise DistributionNotFound(req)

### ISSUE THREAD

**Issue by Senna318** [iancmcc/ouimeaux#104]
Hi Guys,
Tried to install ouimeaux yesterday on my raspberry, using the following steps;
1.	sudo apt-get update  
2.	sudo apt-get upgrade  
3.	sudo apt-get autoremove  
4.	sudo apt-get install gcc-4.8 gcc-4.8-base python-setuptools python-dev   
(source: https://securehomes.esat.kuleuven.be/~decockd/wiki/bin/view.cgi/RaspberryPi/SetupRaspberryPiWithWemoDevices) 
Ouimeaux itself I Installed via git clone https://github.com/iancmcc/ouimeaux.git. So far no problems, already feeling some success since this was already way out of my comfort zone
Then running command ‘wemo list’ gave me the following:
Traceback (most recent call last):
  File "/usr/local/bin/wemo", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: gevent>=1.0
Google learned me a lot, but unfortunately nothing solved the problem. I found several users who encountered exactly the same problem, but for different packages. And if I understand it correctly the problem could in most of the cases be solved with modifications to this package itself. 
Have I missed something simple (used an outdated version or whatever); or did I hit some exceptional situation? All this was done with user root. 

Anyone who could help me with some basic steps? Much appreciated!
Thx!

**Comment by Senna318** [comment]
solution found:
apt-get install python-gevent
