### ISSUE TITLE
ouimeaux server displays ValueErrors

### ISSUE THREAD

**Issue by murraybd** [iancmcc/ouimeaux#114]
This doesn't seem to affect anything but I regularly see this running the ouimeaux server on an Ubuntu 14.04 machine.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/**init**.py", line 271, in error_router
    return original_handler(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
<Greenlet at 0x7fb1e1b127d0: <Flask 'ouimeaux.server'>({'wsgi.websocket': <geventwebsocket.websocket.WebS, <function <lambda> at 0x7fb1e1b88578>)> failed with ValueError

It's not clear to me if it is a flask error or the ouimeaux server code.

**Comment by sstent** [comment]
I had a similar problem, but only with one client. Is looking better since I turned off their antivirus web protector.

**Comment by traindriverrev** [comment]
I'm getting this too, and it's client agnostic.
