### ISSUE TITLE
Switch stopped worked

### ISSUE THREAD

**Issue by MysticRyuujin** [iancmcc/ouimeaux#133]
I've been using the API for a few months now and it suddenly stopped working, I think maybe after doing an apt-get dist-upgrade on Ubuntu 15.10. This is what I'm getting now:

wemo -d switch "Modem" off
Traceback (most recent call last):
  File "/usr/local/bin/wemo", line 9, in <module>
    load_entry_point('ouimeaux==0.7.9.post0', 'console_scripts', 'wemo')()
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux-0.7.9.post0-py2.7.egg/ouimeaux/cli.py", line 361, in wemo
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux-0.7.9.post0-py2.7.egg/ouimeaux/cli.py", line 81, in switch
    scan(args, on_switch)
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux-0.7.9.post0-py2.7.egg/ouimeaux/cli.py", line 29, in scan
    env.start()
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux-0.7.9.post0-py2.7.egg/ouimeaux/environment.py", line 82, in start
    self._process_device(dev, cache=False)
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux-0.7.9.post0-py2.7.egg/ouimeaux/environment.py", line 184, in _process_device
    callback(device)
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux-0.7.9.post0-py2.7.egg/ouimeaux/cli.py", line 78, in on_switch
    getattr(switch, state)()
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux-0.7.9.post0-py2.7.egg/ouimeaux/device/switch.py", line 19, in off
    return self.set_state(0)
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux-0.7.9.post0-py2.7.egg/ouimeaux/device/switch.py", line 12, in set_state
    self.basicevent.SetBinaryState(BinaryState=int(state))
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux-0.7.9.post0-py2.7.egg/ouimeaux/device/api/service.py", line 50, in __call__
    response = requests_post(self.controlURL, body.strip(), headers=self.headers)
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux-0.7.9.post0-py2.7.egg/ouimeaux/utils.py", line 80, in inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.9.1-py2.7.egg/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.9.1-py2.7.egg/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.9.1-py2.7.egg/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.5.109', port=49153): Read timed out. (read timeout=5)

**Comment by MysticRyuujin** [comment]
Apologies, I forced and upgrade via "easy_install -U ouimeaux" and it's working again. I was on 0.7.9 but 0.8.0 appears to have solved the issue, whatever it was :+1:
