### ISSUE TITLE
wemo server command results in Syntax Error on macOS

### ISSUE THREAD

**Issue by ericksonstudio** [iancmcc/ouimeaux#166]
The wemo commands (e.g., status, list, switch) are working. However, running `wemo server` results with this error and does not launch the server:

```
Traceback (most recent call last):
  File "/usr/local/bin/wemo", line 11, in <module>
    load_entry_point('ouimeaux==0.8', 'console_scripts', 'wemo')()
  File "/usr/local/lib/python3.6/site-packages/ouimeaux-0.8-py3.6.egg/ouimeaux/cli.py", line 375, in wemo
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/ouimeaux-0.8-py3.6.egg/ouimeaux/cli.py", line 292, in server
    from socketio.server import SocketIOServer
  File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 108
    except error, ex:
                ^
SyntaxError: invalid syntax
```
My environment is macOS 10.13.1 "High Sierra." Both Python 2.7.10 and 3.6.3 are installed.

**Comment by srivas001** [comment]
I'm getting the same error.

```
$ Traceback (most recent call last):
  File "C:\Users\Stephen\AppData\Local\Programs\Python\Python37-32\Scripts\wemo-script.py", line 11, in <module>
    load_entry_point('ouimeaux==0.8', 'console_scripts', 'wemo')()
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\site-packages\ouimeaux-0.8-py3.7.egg\ouimeaux\cli.py", line 375, in wemo
    args.func(args)
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\site-packages\ouimeaux-0.8-py3.7.egg\ouimeaux\cli.py", line 292, in server
    from socketio.server import SocketIOServer
  File "c:\users\stephen\appdata\local\programs\python\python37-32\lib\site-packages\socketio\server.py", line 108
    except error, ex:
                ^
SyntaxError: invalid syntax
```

My environment is Windows 10 Home, V: 1903, OSBuild: 18362.239,  with Python 3.7.3
