### ISSUE TITLE
TypeError: memoryview: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by vzlgdu** [iancmcc/ouimeaux#199]
Hi, I receive this errors when discovery devices:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gevent/pywsgi.py", line 968, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python3.7/dist-packages/gevent/pywsgi.py", line 916, in run_application
    self.process_result()
  File "/usr/local/lib/python3.7/dist-packages/gevent/pywsgi.py", line 902, in process_result
    self.write(data)
  File "/usr/local/lib/python3.7/dist-packages/gevent/pywsgi.py", line 749, in write
    self._write_with_headers(data)
  File "/usr/local/lib/python3.7/dist-packages/gevent/pywsgi.py", line 770, in _write_with_headers
    self._write(data)
  File "/usr/local/lib/python3.7/dist-packages/gevent/pywsgi.py", line 734, in _write
    self._sendall(data)
  File "/usr/local/lib/python3.7/dist-packages/gevent/pywsgi.py", line 708, in _sendall
    self.socket.sendall(data)
  File "/usr/local/lib/python3.7/dist-packages/gevent/_socket3.py", line 526, in sendall
    data_memory = _get_memory(data)
  File "src/gevent/_greenlet_primitives.py", line 98, in gevent.__greenlet_primitives.get_memory
  File "src/gevent/_greenlet_primitives.py", line 121, in gevent.__greenlet_primitives.get_memory
  File "src/gevent/_greenlet_primitives.py", line 109, in gevent.__greenlet_primitives.get_memory
TypeError: memoryview: a bytes-like object is required, not 'str'
2020-05-09T06:13:25Z {'REMOTE_ADDR': '::ffff:10.0.0.103', 'REMOTE_PORT': '3584', 'HTTP_HOST': '10.0.0.117:8840', (hidden keys: 23)} failed with TypeError

**Comment by 0x78f1935** [comment]
Issue still persists

```
TypeError: memoryview: a bytes-like object is required, not 'str'
2020-08-18T10:20:07Z {'REMOTE_ADDR': '192.168.1.3', 'REMOTE_PORT': '48704', 'HTTP_HOST': 'portal.my-jewellery.business', (hidden keys: 33)} failed with TypeError

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 970, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python3.8/site-packages/geventwebsocket/handler.py", line 82, in run_application
    self.process_result()
  File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 904, in process_result
    self.write(data)
  File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 751, in write
    self._write_with_headers(data)
  File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 772, in _write_with_headers
    self._write(data)
  File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 734, in _write
    self._sendall(data)
  File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 708, in _sendall
    self.socket.sendall(data)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socket3.py", line 533, in sendall
    data_memory = _get_memory(data)
```

Incoming data
```
2020-08-18T10:22:51Z {'REMOTE_ADDR': '192.168.1.3', 'REMOTE_PORT': '49710', 'HTTP_HOST': 'somewebsite.com', (hidden keys: 33)} failed with TypeError
```
Seems like the json comes in as string
