### ISSUE TITLE
Can't listen on IPv6

### ISSUE THREAD

**Issue by andrewpollock** [iancmcc/ouimeaux#30]
I wanted to have the server listen on IPv6, so I tried putting

```
bind: :::5000
```

in my configuration, but it blew up:

```
$ wemo server
Traceback (most recent call last):
  File "/usr/local/bin/wemo", line 9, in <module>
    load_entry_point('ouimeaux==0.7.2', 'console_scripts', 'wemo')()
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux/cli.py", line 191, in wemo
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux/cli.py", line 123, in server
    initialize()
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux/server/__init__.py", line 30, in initialize
    ENV.start()
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux/environment.py", line 81, in start
    self.upnp.server.start()
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 234, in start
    self.init_socket()
  File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 118, in init_socket
    self.socket = self.get_listener(self.address, self.family)
  File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 128, in get_listener
    return _udp_socket(address, reuse_addr=self.reuse_addr, family=family)
  File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 171, in _udp_socket
    sock.bind(address)
  File "<string>", line 1, in bind
socket.gaierror: [Errno -9] Address family for hostname not supported: ('::', 5000)
```

**Comment by onbiron** [comment]
Is there any progress on this issue? I can't manage to list devices on an IPv6 network.
