### ISSUE TITLE
Exception on receiving Signal Events in Python 

### ISSUE THREAD

**Issue by chriswhsu** [iancmcc/ouimeaux#42]
I am trying to subscribe to a switch on or off event and am running the basic example code provided:

``` python
#!/usr/bin/env python

from ouimeaux.environment import Environment
from ouimeaux.signals import statechange, receiver

env = Environment()
env.start()
env.discover(10)

switch = env.get_switch('WeMo Insight')

@receiver(statechange, sender=switch)
def switch_toggle(device, **kwargs):
    print device, kwargs['state']


env.wait()  # Pass control to the event loop
```

The device is found and the process waits for an event.  But when I turn the switch on or off I receive the following exception, instead of a simple print of the state of the device:

```
chriswhsu@ubuntu:~/wemo$ sudo python run.py 

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 508, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 495, in run_application
    self.process_result()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 484, in process_result
    for data in self.result:
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux/subscribe.py", line 66, in _handle
    subscription.send(device, type=property_.tag, value=text)
  File "/usr/local/lib/python2.7/dist-packages/pysignals/dispatcher.py", line 197, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux/signals.py", line 26, in _got_subscription
    statechange.send(sender, state=int(kwargs['value']))
  File "/usr/local/lib/python2.7/dist-packages/pysignals/dispatcher.py", line 197, in send
    response = receiver(signal=self, sender=sender, **named)
TypeError: switch_toggle() takes exactly 1 argument (0 given)
{'CONTENT_LENGTH': '186',
 'CONTENT_TYPE': 'text/xml; charset="utf-8"',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_HOST': '192.168.1.43:8989',
 'HTTP_NT': 'upnp:event',
 'HTTP_NTS': 'upnp:propchange',
 'HTTP_SEQ': '5',
 'HTTP_SID': 'uuid:9425c3b4-1dd1-11b2-b845-84d51325eaab',
 'PATH_INFO': '/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '192.168.1.29',
 'REMOTE_PORT': '3409',
 'REQUEST_METHOD': 'NOTIFY',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'localhost',
 'SERVER_PORT': '8989',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.0 Python/2.7',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7f91e6d05270>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x284fbd0>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with TypeError
```

Any help would be greatly appreciated.

Ubuntu 12.04
Python 2.7.3 
[GCC 4.6.3] on linux2

**Comment by randywreed** [comment]
This probably does requires a documentation change as the OPs initial code matches the documentation, but the correct code does not.

documentation:
`Example: Registering a handler for when a Light Switch switches on or off:

from ouimeaux.signals import statechange, receiver

env = Environment(); env.start()
env.discover(5)

switch = env.get_switch('Porch Light')

@receiver(statechange, sender=switch)
def switch_toggle(device, **kwargs):
    print device, kwargs['state']

env.wait()  # Pass control to the event loop`
