### ISSUE TITLE
Issue with Wemo cache

### ISSUE THREAD

**Issue by chasingtheflow** [iancmcc/ouimeaux#62]
Not sure what is going on exactly, but when I use the wemo command to toggle a switch, for example `wemo switch 'Lights' on`, it works the first time. But when I try to issue the reverse command, `wemo switch 'Lights' off`, I receive an error. Running `wemo clear` and then running the command again works, but is hardly practical. I'm not really sure what's going on with my setup, as the exact same script works correctly on another machine I have. Below is the traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/wemo", line 9, in <module>
    load_entry_point('ouimeaux==0.7.3', 'console_scripts', 'wemo')()
  File "/usr/local/lib/python2.7/site-packages/ouimeaux/cli.py", line 194, in wemo
    args.func(args)
  File "/usr/local/lib/python2.7/site-packages/ouimeaux/cli.py", line 81, in switch
    scan(args, on_switch)
  File "/usr/local/lib/python2.7/site-packages/ouimeaux/cli.py", line 29, in scan
    env.start()
  File "/usr/local/lib/python2.7/site-packages/ouimeaux/environment.py", line 78, in start
    self._process_device(dev, cache=False)
  File "/usr/local/lib/python2.7/site-packages/ouimeaux/environment.py", line 156, in _process_device
    with get_cache() as c:
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/ouimeaux/config.py", line 115, in get_cache
    with closing(shelve.open(filename, writeback=True)) as cache:
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 239, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 223, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
gdbm.error: (35, 'Resource temporarily unavailable')
```

Let me know if there's something I'm doing wrong or any ideas on how to get this fixed.

Thanks!

**Comment by eldridgejm** [comment]
I've submitted a pull request that (hopefully) fixes this issue. The problem seems to be that the cache file is opened twice without closing it. Namely, the cache file is still open when `self._process_device` is called in `Environment.start`, and `self._process_device` calls `get_cache()` again, opening the cache once more.

I noticed that `get_cache` uses a `gevent.RLock`, allowing a thread to acquire the lock numerous times. Perhaps this can be switched to a normal lock now, since even the same thread opening the cache file seems to cause problems.

Note that I encountered this problem on OS X Yosemite with Python installed with `brew`. I didn't have the issue on Arch Linux. Perhaps the backend used by `shelve` is different across OSs, causing the difference.

Anyways, I'm new to pull requests. Let me know if I should've done something differently.

**Comment by chasingtheflow** [comment]
Awesome, thanks all -- really appreciate the effort on this. I'm not exactly a pip ninja, but now that this is in the master branch, is there a convenient way for me to get it to see if this fixes my issue? Or do I need to wait for a release / when might that be? Thanks :-)

**Comment by iancmcc** [comment]
Hmm, should probably do a release sometime soon. Let me see if I can get a few more tickets closed first, but either way I'll release the next version this weekend.

**Comment by iancmcc** [comment]
You can also always just check out the repo, cd to it, and do "pip install -e .", which will install it in development mode from the source. Then you can just "git pull" to get the latest code.

**Comment by chasingtheflow** [comment]
Awesome, thanks @iancmcc

**Comment by chasingtheflow** [comment]
Just installed using `pip install -e .` as described and all is working for me now, thanks again all :+1:
