### ISSUE TITLE
Problem with SSLv3?

### ISSUE THREAD

**Issue by fniemeyer** [iancmcc/ouimeaux#87]
I'm currently using OSMC Release Candidate - which is based on Debian Jessie - with Python 2.7.9. When trying to execute any "wemo"-command (e.g "wemo list") I get the following error:

osmc@osmc:~$ wemo list
Traceback (most recent call last):
  File "/usr/local/bin/wemo", line 9, in <module>
    load_entry_point('ouimeaux==0.7.9-r0', 'console_scripts', 'wemo')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['**name**'])
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux-0.7.9_r0-py2.7.egg/ouimeaux/cli.py", line 6, in <module>
    from .discovery import UPnPLoopbackException
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux-0.7.9_r0-py2.7.egg/ouimeaux/discovery.py", line 4, in <module>
    from gevent import socket
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.1-py2.7-linux-armv7l.egg/gevent/socket.py", line 659, in <module>
    from gevent.ssl import sslwrap_simple as ssl, SSLError as sslerror, SSLSocket as SSLType
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.1-py2.7-linux-armv7l.egg/gevent/ssl.py", line 386, in <module>
    def get_server_certificate(addr, ssl_version=PROTOCOL_SSLv3, ca_certs=None):
NameError: name 'PROTOCOL_SSLv3' is not defined

With OSMC Alpha 4 und Python 2.7.8 everything was working fine.

**Comment by jacobtardieu** [comment]
I just had the same issue on my Debian Jessie. Looks like the bug was in `gevent`: https://github.com/gevent/gevent/issues/513. This is now fixed in `gevent` 1.0.2. 
To fix `ouimeaux`, install this `gevent` version (for this you may have to uninstall the `python-gevent` debian package to install `gevent` via pip : `apt remove python-gevent`, `pip install gevent`).
