### ISSUE TITLE
crash when running wemo

### ISSUE THREAD

**Issue by cbrake** [iancmcc/ouimeaux#91]
any thoughts what I'm doing wrong:

```
[cbrake@happy ~]$ more /usr/bin/wemo 
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'ouimeaux==0.7.9.post0','console_scripts','wemo'
__requires__ = 'ouimeaux==0.7.9.post0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('ouimeaux==0.7.9.post0', 'console_scripts', 'wemo')()
    )
[cbrake@happy ~]$ wemo list
Traceback (most recent call last):
  File "/usr/bin/wemo", line 9, in <module>
    load_entry_point('ouimeaux==0.7.9.post0', 'console_scripts', 'wemo')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2672, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2345, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2351, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/ouimeaux-0.7.9.post0-py3.4.egg/ouimeaux/cli.py", line 43
    should call back during discovery.""".strip()
                                        ^
SyntaxError: invalid syntax
```

Thanks!

**Comment by rgardner** [comment]
`ouimeaux` doesn't support Python 3 (just try pip3 install ouimeaux and you should get a build error due to gevent). As most of the above console output references python3, that seems to be the source of your issue.

**Comment by Fudoka** [comment]
I'm getting the same error.

You say that ouimeaux doesn't support Python 3 but `easy-install ouimeaux` failed to find Python.h despite having python-devel for Python 2.7 installed.
I installed python3-devel and then `easy-install ouimeaux` (seemed) to run OK but when I run `wemo` I get this same SyntaxError 

How can I resolve this?

I'm running openSUSE 13.2 with Python 2.7

**Comment by drock371** [comment]
Python 3 support was added in v0.8.
