### ISSUE TITLE
env.start() stalls completely

### ISSUE THREAD

**Issue by talldean** [iancmcc/ouimeaux#93]
```
env = Environment()
print 'foo'
env.start()
print 'bar'
```
That never gets to bar; it's stalling at `env.start()`.  The same script worked last week; just tried a restart, and no love.  Any idea what I should check on a linux box/what to look for?

**Comment by talldean** [comment]
Left it run for 20+ minutes, then ctrl-c; here's the stack.

```
^CTraceback (most recent call last):
  File "./lights.py", line 254, in <module>
    bridge = get_bridge()
  File "./lights.py", line 41, in get_bridge
    env.start()
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux-0.7.9_r0-py2.7.egg/ouimeaux/environment.py", line 82, in start
    self._process_device(dev, cache=False)
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux-0.7.9_r0-py2.7.egg/ouimeaux/environment.py", line 169, in _process_device
    self.registry.register(device)
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux-0.7.9_r0-py2.7.egg/ouimeaux/subscribe.py", line 35, in register
    self._resubscribe(device.basicevent.eventSubURL)
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux-0.7.9_r0-py2.7.egg/ouimeaux/subscribe.py", line 48, in _resubscribe
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/ouimeaux-0.7.9_r0-py2.7.egg/ouimeaux/utils.py", line 84, in inner
    gevent.sleep(delay)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1a1-py2.7-linux-armv5tel.egg/gevent/hub.py", line 89, in sleep
    hub.wait(loop.timer(seconds, ref=ref))
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1a1-py2.7-linux-armv5tel.egg/gevent/hub.py", line 360, in wait
    result = waiter.get()
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1a1-py2.7-linux-armv5tel.egg/gevent/hub.py", line 587, in get
    return self.hub.switch()
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1a1-py2.7-linux-armv5tel.egg/gevent/hub.py", line 350, in switch
    return greenlet.switch(self)
```

**Comment by talldean** [comment]
Okay, walking that back, it's trying to subscribe to something over the network, and failing to connect.  

Anyone else hit the same recently with no other changes?

Looking at the logging:
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 10.0.0.29

**Comment by talldean** [comment]
Looking at 10.0.0.29 and ruling the network out, from the same machine:

```
$ wget http://10.0.0.29:49153/eventservice.xml
--2015-07-11 13:39:32--  http://10.0.0.29:49153/eventservice.xml
Connecting to 10.0.0.29:49153... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18166 (18K) [text/xml]
Saving to: `eventservice.xml'

100%[=====================================================================================>] 18,166      --.-K/s   in 0.005s  

2015-07-11 13:39:32 (3.37 MB/s) - `eventservice.xml' saved [18166/18166]

deanj@DebianPlug:~$ more eventservice.xml 
<?xml version="1.0"?>
<scpd xmlns="urn:Belkin:service-1-0">

  <specVersion>
    <major>1</major>
    <minor>0</minor>
  </specVersion>
...
```

**Comment by talldean** [comment]
```wemo clear``` cleared the cache and seems to have fixed whatever was off here.  Win.
